feat: Added logic to apply to users with 3 or referrals
tumavideo/yop pull request #103
Opened 2023-11-24 18:19 UTC by Mwimwii

### feat: Added logic to apply to users with 3 or referrals

- Added a count on the referrals table to get the number of referred users per account
- Added a Folder icon for small screens
- Users can upload resumes by name
- Placeholder icon to represent file uploaded
- Removed emojis in place for the 💡
- Limited the uploads to 3 resumes

2023-11-29 07:43 UTC, anthonysikaneta requested changes

2023-11-29 07:43 UTC, anthonysikaneta commented on app/profile/update-profile-form.tsx
>        console.log(error);
We should probably show toast for the error, no?

2023-11-29 07:43 UTC, anthonysikaneta commented on app/profile/update-profile-form.tsx
> +  const [resume, setResume] = useState(null);
What is the distinction between the individual resume and the collection of resume? In terms of content? Array of string vs. object? TypeScript interface needed here.

2023-11-29 07:43 UTC, anthonysikaneta commented on app/profile/update-profile-form.tsx
> +          .sort((a, b) => {
use toSorted...

2023-11-29 07:43 UTC, anthonysikaneta commented on app/profile/update-profile-form.tsx
> +          .slice(0, 3);
...and toSpliced. These won't modify the original object.

2023-11-29 07:43 UTC, anthonysikaneta commented on app/profile/update-profile-form.tsx
> +    // await supabase.auth.updateUser({
nitpick: let's not leave commented code for the ghosts

2023-11-29 07:43 UTC, anthonysikaneta commented on app/profile/update-profile-form.tsx
> +                      {resume.split("/")[1]}
You've this split function four times. Define it once in a function / utility and name it so that its' purpose is obvious.

2023-11-29 07:43 UTC, anthonysikaneta commented on app/styles/animations.css
> +}
If we're going to use .css then please let's use .scss like TW does...

2023-11-29 07:43 UTC, anthonysikaneta commented on app/profile/update-profile-form.tsx
> +      .getPublicUrl(`${id}/${fileName}`, {
How does the versioning happen if the filename is always the same?

2023-11-30 08:36 UTC, Mwimwii commented on app/profile/update-profile-form.tsx
> +      .getPublicUrl(`${id}/${fileName}`, {
Please elaborate

2023-12-06 12:02 UTC, Mwimwii commented on app/profile/update-profile-form.tsx
> +          .sort((a, b) => {
Done

2023-12-06 12:03 UTC, Mwimwii commented on app/profile/update-profile-form.tsx
> +    // await supabase.auth.updateUser({
Done

2023-12-06 12:08 UTC, Mwimwii commented on app/profile/update-profile-form.tsx
>        console.log(error);
Done

2023-12-06 14:59 UTC, tonydollarsign approved these changes
This is the best code I've ever seen in my life

2023-12-06 15:12 UTC, tonydollarsign approved these changes

2023-12-06 15:14 UTC, merged